-- <nowiki>
-- Primary data for all regular spirits and elders
-- Translations should **NOT** be added to this file -- this file should always
-- be identical across all wikis.
-- Instead, a language-specific subfile provides all translated text.
-- Only variables ending in 'name' will ever need to be translated.
local data = {
	
	-- Base / Basic / Default 
	basic_hair = {
		name			= "Base Hair",
		alt_name		= { "Basic Hair", "Default Hair", "Base Hair A", "Basic Hair A", "Default Hair A", "Moth Hair" },
		item_type		= "hair",
		icon			= "Icon_hair_default.png",
		real			= "Hair02-Default.png",
		side			= "Hair-Base-1-side.png",
		back			= "Hair-Base-1-back.png",
		price			= "free",
	},
	basic_hair_b = {
		name			= "Base Hair B",
		alt_name		= { "Basic Hair B", "Default Hair B" },
		item_type		= "hair",
		icon			= "Base-Hair-2-Ray.png",
		real			= "Hair-Base_2.png",
		side			= "",
		back			= "",
		price			= "free",
	},
	basic_hair_c = {
		name			= "Base Hair C",
		alt_name		= { "Basic Hair C", "Default Hair C" },
		item_type		= "hair",
		icon			= "Base-Hair-3-Ray.png",
		real			= "Hair-Base_3.png",
		side			= "",
		back			= "",
		price			= "free",
	},
	basic_mask = {
		name			= "Base Mask C",
		alt_name		= { "Basic Mask C", "Default Mask C" },
		item_type		= "mask",
		icon			= "Icon_mask_default.png",
		real			= "Mask01-no_mask.png",
		side			= "",
		price			= "free",
	},
	basic_cape = {
		name			= "Base Cape",
		alt_name		= { "Basic Cape", "Default Cape" },
		item_type		= "cape",
		icon			= "Icon_cape_brown-Morybel-0146.png",
		real			= "Cape_brown_2.png",
		front			= "Cape-Brown_Default.png",
		interior		= "Cape_brown_3.png",
		exterior		= "",
		price			= "free",
	},
	basic_outfit = {
		name			= "Base Outfit",
		alt_name		= { "Basic Outfit", "Default Outfit" },
		item_type		= "outift",
		icon			= "Icon_pants_default.png",
		real			= "Legs01-Default.png",
		back			= "",
		price			= "free",
	},
	basic_footwear = {
		name			= "Base Shoes",
		alt_name		= { "Basic Shoes", "Default Shoes", "No Shoes", "Barefoot" },
		item_type		= "footwear",
		icon			= "No-cosmetic.png",
		real			= "Basic-Barefoot-no-shoes.png",
		price			= "free",
	},

	--
	-- REGULAR SPIRITS
	--
	
	-- Isle
	pointing_candlemaker_hair = {
		name			= "Pointing Candlemaker Hair",
		item_type		= "hair",
		spirit          = "Pointing Candlemaker",
		icon			= "PointingCandlemaker-2.png",
		real			= "Hair18-Short_Cowlick.png",
		side            = "",
		back            = "",
		price			= "free",
	},
	pointing_candlemaker_outfit = {
		name			= "Pointing Candlemaker Outfit",
		item_type		= "outfit",
		spirit          = "Pointing Candlemaker",
		icon			= "PointingCandlemaker-3.png",
		real			= "Legs07.png",
		back			= "",
		price			= "4 H",
	},
	rejecting_voyager_hair = {
		name			= "Rejecting Voyager Hair",
		item_type		= "hair",
		spirit			= "Rejecting Voyager",
		icon			= "RejectingVoyager-2.png",
		real			= "Hair34-One_Side_Short.png",
		side			= "",
		back			= "",
		price			= "1 H",
	},
	rejecting_voyager_facepiece = {
		name			= "Rejecting Voyager Face Accessory",
		item_type		= "facepiece",
		spirit			= "Rejecting Voyager",
		icon			= "RejectingVoyager-3.png",
		real			= "Mask02-Simple_horizontal.png",
		side			= "",
		price			= "3 H",
	},
	ushering_stargazer_hair = {
		name			= "Ushering Stargazer Hair",
		item_type		= "hair",
		spirit			= "Ushering Stargazer",
		icon			= "UsheringStargazer-2.png",
		real			= "Hair06-Single_Ponytail.png",
		side			= "",
		back			= "",
		price			= "free",
	},
	ushering_stargazer_outfit = {
		name			= "Ushering Stargazer Outfit",
		item_type		= "outfit",
		spirit			= "Ushering Stargazer",
		icon			= "UsheringStargazer-3.png",
		real			= "Legs06.png",
		back			= "",
		price			= "4 H",
	},
	
	-- Prairie
	applauding_bellmaker_hair = {
		name			= "Applauding Bellmaker Hair",
		item_type		= "hair",
		spirit			= "Applauding Bellmaker",
		icon			= "ApplaudingBellmaker-2.png",
		real			= "Hair05-Pippi_Ponytails.png",
		side			= "Applauding-Bellmaker-Hair-side.png",
		back			= "Applauding-Bellmaker-Hair-back.png",
		price			= "3 H",
	},
	bird_whisperer_hair = {
		name			= "Bird Whisperer Hair",
		item_type		= "emote",
		spirit			= "Bird Whisperer",
		icon			= "BirdWhisperer-3.png",
		real			= "Hair11-Vertical_Ponytail.png",
		side			= "Bird-Whisperer-Hair-side.png",
		back			= "Bird-Whisperer-Hair-back.png",
		price			= "5 H",
	},
	bird_whisperer_music = {
		name			= "Bird Whisperer Music",
		item_type		= "music",
		name			= "Bird Whisperer",
		music_tag		= "N",
		music_id		= "1",
		price			= "1 H",
	},
	butterfly_charmer_cape = {
		name			= "Butterfly Charmer Cape",
		item_type		= "cape",
		spirit			= "Butterfly Charmer",
		icon			= "ButterflyCharmer-2-Morybel-0146.png",
		real			= "Cape_yellow_2.png",
		front			= "Cape-Yellow.png",
		interior		= "Cape_yellow_3.png",
		exterior		= "",
		price			= "3 H",
	},
	butterfly_charmer_cape_2 = {
		name			= "Butterfly Charmer Tier 2 Cape",
		item_type		= "cape_2",
		spirit			= "Butterfly Charmer",
		icon			= "ButterflyCharmer-3.png",
		real			= "Cape_yellow_tier_2_back.png",
		front			= "Cape_yellow_tier_2_front.png",
		interior		= "Cape_yellow_tier_2_inner.png",
		exterior		= "",
		price			= "9 H",
	},
	butterfly_charmer_outfit = {
		name			= "Butterfly Charmer Outfit",
		item_type		= "outfit",
		spirit			= "Butterfly Charmer",
		icon			= "ButterflyCharmer-4.png",
		real			= "Legs08.png",
		back			= "",
		price			= "4 H",
	},
	exhausted_dock_worker_facepiece = {
		name			= "Exhausted Dock Worker Face Accessory",
		item_type		= "facepiece",
		spirit			= "Exhausted Dock Worker",
		icon			= "ExhaustedDockWorker-2.png",
		real			= "Mask04.png",
		side			= "",
		price			= "3 H",
	},
	laughing_light_catcher_hair = {
		name			= "Laughing Light Catcher Hair",
		item_type		= "hair",
		spirit			= "Laughing Light Catcher",
		icon			= "LaughingLightCatcher-3.png",
		real			= "Hair26-Puffy_Ponytails.png",
		side			= "Laughing-Light-Catcher-Hair-side.png",
		back			= "Laughing-Light-Catcher-Hair-back.png",
		price			= "5 H",
	},
	laughing_light_catcher_instrument = {
		name			= "Harp",
		alt_name		= { "Laughing Light Catcher Instrument" },
		item_type		= "instrument",
		spirit			= "Laughing Light Catcher",
		icon			= "LaughingLightCatcher-2.png",
		real			= "Laughing-Light-Catcher-harp.png",
		held			= "Instrument_harp_playing.png",
		back			= "Instrument-Harp.png",
		price			= "5 H",
	},
	slumbering_shipwright_hair = {
		name			= "Slumbering Shipwright Hair",
		item_type		= "hair",
		spirit			= "Slumbering Shipwright",
		icon			= "SlumberingShipwright-2.png",
		real			= "Slumbering-Shipwright-Hair-front.png",
		side			= "Hair37-Mid_Mohawk.png",
		back			= "Slumbering-Shipwright-Hair-back.png",
		price			= "3 H",
	},
	waving_bellmaker_hair = {
		name			= "Waving Bellmaker Hair",
		item_type		= "hair",
		spirit			= "Waving Bellmaker",
		icon			= "WavingBellmaker-2.png",
		real			= "Hair10-Small_Tuft.png",
		side			= "",
		back			= "",
		price			= "2 H",
	},
	waving_bellmaker_mask = {
		name			= "Waving Bellmaker Mask",
		item_type		= "mask",
		spirit			= "Waving Bellmaker",
		icon			= "WavingBellmaker-3.png",
		real			= "Mask03.png",
		side			= "",
		price			= "5 H",
	},
	
	-- Forest
	apologetic_lumberjack_hair = {
		name			= "Apologetic Lumberjack Hair",
		item_type		= "hair",
		spirit			= "Apologetic Lumberjack",
		icon			= "ApologeticLumberjack-2.png",
		real			= "Hair07-Short_Ponytails.png",
		side			= "",
		back			= "",
		price			= "3 H",
	},
	apologetic_lumberjack_facepiece = {
		name			= "Apologetic Lumberjack Face Accessory",
		item_type		= "facepiece",
		spirit			= "Apologetic Lumberjack",
		icon			= "ApologeticLumberjack-3.png",
		real			= "Mask05-Diamond.png",
		side			= "",
		price			= "5 H",
	},
	blushing_prospector_hair = {
		name			= "Blushing Prospector Hair",
		item_type		= "hair",
		spirit			= "Blushing Prospector",
		icon			= "BlushingProspector-2.png",
		real			= "Hair32-Pigtail_Braids.png",
		side			= "",
		back			= "",
		price			= "3 H",
	},
	blushing_prospector_instrument = {
		name			= "Drum",
		alt_name		= { "Blushing Prospector Instrument" },
		item_type		= "instrument",
		spirit			= "Blushing Prospector",
		icon			= "BlushingProspector-3.png",
		real			= "Blushing_Prospector-Drum.png",
		held			= "Instrument_drum_playing.png",
		back			= "nstrument-High_Drum.png",
		price			= "5 H",
	},
	dismayed_hunter_cape = {
		name			= "Dismayed Hunter Cape",
		item_type		= "cape",
		spirit			= "Dismayed Hunter",
		icon			= "DismayedHunter-3-Morybel-0146.png",
		real			= "Cape_purple_2.png",
		front			= "Cape-Purple.png",
		interior		= "Cape_purple_3.png",
		exterior		= "",
		price			= "30 H",
	},
	dismayed_hunter_cape_2 = {
		name			= "Dismayed Hunter Tier 2 Cape",
		item_type		= "cape_2",
		spirit			= "Dismayed Hunter",
		icon			= "DismayedHunter-4.png",
		real			= "Cape_purple_tier_2_back.png",
		front			= "Cape_purple_tier_2_front.png",
		interior		= "Cape_purple_tier_2_inner.png",
		exterior		= "",
		price			= "90 H",
	},
	dismayed_hunter_hair = {
		name			= "Dismayed Hunter Hair",
		item_type		= "hair",
		spirit			= "Dismayed Hunter",
		icon			= "DismayedHunter-2.png",
		real			= "Hair17-Thick_Ponytails.png",
		side			= "",
		back			= "",
		price			= "5 H",
	},
	hidenseek_pioneer_hair = {
		name			= "Hide'n'Seek Pioneer Hair",
		item_type		= "hair",
		spirit			= "Hide'n'Seek Pioneer",
		icon			= "HideNSeekPioneer-2.png",
		real			= "Hair14-Bob.png",
		side			= "",
		back			= "",
		price			= "2 H",
	},
	hidenseek_pioneer_mask = {
		name			= "Hide'n'Seek Pioneer Mask",
		alt_name		= { "Chibi Mask" },
		item_type		= "mask",
		spirit			= "Hide'n'Seek Pioneer",
		icon			= "HideNSeekPioneer-3.png",
		real			= "Mask06-small-chibi.png",
		side			= "",
		price			= "20 H",
	},
	hidenseek_pioneer_outfit = {
		name			= "Hide'n'Seek Pioneer Outfit",
		item_type		= "outfit",
		spirit			= "Hide'n'Seek Pioneer",
		icon			= "HideNSeekPioneer-4.png",
		real			= "Legs_hide_n_seek_pioneer_dress.png",
		back			= "",
		price			= "15 H",
	},
	pouty_porter_cape = {
		name			= "Pouty Porter Cape",
		exterior		= "",
		item_type		= "cape",
		spirit			= "Pouty Porter",
		icon			= "PoutyPorter-3-Morybel-0146.png",
		real			= "Cape_teal2.png",
		front			= "Cape-Teal.png",
		interior		= "Cape_teal3.png",
		exterior		= "",
		price			= "20 H",
	},
	pouty_porter_cape_2 = {
		name			= "Pouty Porter Tier 2 Cape",
		item_type		= "cape_2",
		spirit			= "Pouty Porter",
		icon			= "PoutyPorter-4.png",
		real			= "Cape_teal_tier_2_back.png",
		front			= "Cape_teal_tier_2_front.png",
		interior		= "Cape_teal_tier_2_inner.png",
		exterior		= "",
		price			= "60 H",
	},
	pouty_porter_hair = {
		name			= "Pouty Porter Hair",
		item_type		= "hair",
		spirit			= "Pouty Porter",
		icon			= "PoutyPorter-2.png",
		real			= "Hair35-One_Side_Medium.png",
		side			= "",
		back			= "",
		price			= "3 H",
	},
	shivering_trailblazer_hair = {
		name			= "Shivering Trailblazer Hair",
		item_type		= "hair",
		spirit			= "Shivering Trailblazer",
		icon			= "ShiveringTrailblazer-3.png",
		real			= "Hair08-Wispy.png",
		side			= "",
		back			= "",
		price			= "5 H",
	},
	shivering_trailblazer_outfit = {
		name			= "Shivering Trailblazer Outfit",
		item_type		= "outfit",
		spirit			= "Shivering Trailblazer",
		icon			= "ShiveringTrailblazer-2.png",
		real			= "Legs03.png",
		back			= "",
		price			= "2 H",
	},
	tearful_light_miner_hair = {
		name			= "Tearful Light Miner Hair",
		item_type		= "hair",
		spirit			= "Tearful Light Miner",
		icon			= "TearfulLightMiner-2.png",
		real			= "Hair38-Short_Mullet.png",
		side			= "",
		back			= "",
		price			= "3 H",
	},
	whale_whisperer_music = {
		name			= "Whale Whisperer Music",
		item_type		= "music",
		spirit			= "Whale Whisperer",
		music_tag		= "W",
		music_id		= "2",
		price			= "2 H",
	},
	
	-- Valley
	backflipping_champion_hair = {
		name			= "Backflipping Champion Hair",
		item_type		= "hair",
		spirit			= "Backflipping Champion",
		icon			= "BackflippingChampion-2.png",
		real			= "Hair12-Chris_Hair.png",
		side			= "",
		back			= "",
		price			= "5 H",
	},
	backflipping_champion_facepiece = {
		name			= "Backflipping Champion Face Accessory",
		item_type		= "facepiece",
		spirit			= "Backflipping Champion",
		icon			= "BackflippingChampion-3.png",
		real			= "Mask08.png",
		side			= "",
		price			= "5 H",
	},
	bowing_medalist_hair = {
		name			= "Bowing Medalist Hair",
		item_type		= "hair",
		spirit			= "Bowing Medalist",
		icon			= "BowingMedalist-2.png",
		real			= "Hair04-Lions_Mane_Hair.png",
		side			= "",
		back			= "",
		price			= "5 H",
	},
	bowing_medalist_facepiece = {
		name			= "Bowing Medalist Face Accessory",
		item_type		= "facepiece",
		spirit			= "Bowing Medalist",
		icon			= "BowingMedalist-3.png",
		real			= "Mask09.png",
		side			= "",
		price			= "5 H",
	},
	cheerful_spectator_hair = {
		name			= "Cheerful Spectator Hair",
		item_type		= "hair",
		spirit			= "Cheerful Spectator",
		icon			= "CheerfulSpectator-2.png",
		real			= "Hair28-Afro.png",
		side			= "",
		back			= "",
		price			= "5 H",
	},
	cheerful_spectator_instrument = {
		name			= "Piano",
		alt_name		= { "Cheerful Spectator Instrument" },
		item_type		= "instrument",
		spirit			= "Cheerful Spectator",
		icon			= "CheerfulSpectator-3.png",
		real			= "Cheerful-Spectator-Piano.png",
		held			= "Instrument_piano_playing.png",
		back			= "Instrument-Toy_Piano.png",
		price			= "10 H",
	},
	confident_sightseer_hair = {
		name			= "Confident Sightseer Hair",
		item_type		= "hair",
		spirit			= "Confident Sightseer",
		icon			= "ConfidentSightseer-2.png",
		real			= "Hair03-Wedge_Cut.png",
		side			= "",
		back			= "",
		price			= "2 H",
	},
	confident_sightseer_outfit = {
		name			= "Confident Sightseer Outfit",
		item_type		= "outfit",
		spirit			= "Confident Sightseer",
		icon			= "ConfidentSightseer-3.png",
		real			= "Legs05.png",
		back			= "",
		price			= "5 H",
	},
	handstanding_thrillseeker_cape = {
		name			= "Handstanding Thrillseeker Cape",
		item_type		= "cape",
		spirit			= "Handstanding Thrillseeker",
		icon			= "HandstandingThrillseeker-2-Morybel-0146.png",
		real			= "Cape_pink_2.png",
		front			= "Cape-Pink.png",
		interior		= "Cape_pink_3.png",
		exterior		= "",
		price			= "40 H",
	},
	handstanding_thrillseeker_cape_2 = {
		name			= "Handstanding Thrillseeker Tier 2 Cape",
		item_type		= "cape_2",
		spirit			= "Handstanding Thrillseeker",
		icon			= "HandstandingThrillseeker-tier-2.png",
		real			= "Cape_pink_tier_2_back.png",
		front			= "Ascended_pink_cape.PNG",
		interior		= "Cape_pink_tier_2_inner.png",
		exterior		= "",
		price			= "120 H",
	},
	manta_whisperer_music = {
		name			= "Manta Whisperer Music",
		item_type		= "music",
		spirit			= "Manta Whisperer",
		music_tag		= "D",
		music_id		= "3",
		price			= "3 H",
	},
	proud_victor_cape = {
		name			= "Proud Victor Cape",
		item_type		= "cape",
		spirit			= "Proud Victor",
		icon			= "ProudVictor-2-Morybel-0146.png",
		real			= "Cape_red_3.png",
		front			= "Cape-Red.png",
		interior		= "Cape_red_2.png",
		exterior		= "",
		price			= "10 H",
	},
	proud_victor_cape_2 = {
		name			= "Proud Victor Tier 2 Cape",
		item_type		= "cape_2",
		spirit			= "Proud Victor",
		icon			= "ProudVictor-4.png",
		real			= "Cape_red_tier_2_back.png",
		front			= "Cape_red_tier_2_front.png",
		interior		= "Cape_red_tier_2_inner.png",
		exterior		= "",
		price			= "30 H",
	},
	proud_victor_mask = {
		name			= "Proud Victor Mask",
		item_type		= "mask",
		spirit			= "Proud Victor",
		icon			= "ProudVictor-3.png",
		real			= "Mask07-No_Face.png",
		side			= "",
		price			= "30 H",
	},
	
	-- Wasteland
	courageous_soldier_cape = {
		name			= "Courageous Soldier Cape",
		item_type		= "cape",
		spirit			= "Courageous Soldier",
		icon			= "CourageousSoldier-3-Morybel-0146.png",
		real			= "Cape_green2.png",
		front			= "Cape-Green.png",
		interior		= "Cape_green3.png",
		exterior		= "",
		price			= "15 H",
	},
	courageous_soldier_cape_2 = {
		name			= "Courageous Soldier Tier 2 Cape",
		item_type		= "cape_2",
		spirit			= "Courageous Soldier",
		icon			= "CourageousSoldier-4.png",
		real			= "Cape_green_tier_2_back.png",
		front			= "Cape_green_tier_2_front.png",
		interior		= "Cape_green_tier_2_inner.png",
		exterior		= "",
		price			= "45 H",
	},
	courageous_soldier_hair = {
		name			= "Courageous Soldier Hair",
		item_type		= "hair",
		spirit			= "Courageous Soldier",
		icon			= "CourageousSoldier-2.png",
		real			= "Hair13-Short_Mohawk.png",
		side			= "",
		back			= "",
		price			= "4 H",
	},
	fainting_warrior_hair = {
		name			= "Fainting Warrior Hair",
		item_type		= "hair",
		spirit			= "Fainting Warrior",
		icon			= "FaintingWarrior-2.png",
		real			= "Hair36-One_Side_Long.png",
		side			= "",
		back			= "",
		price			= "5 H",
	},
	fainting_warrior_mask = {
		name			= "Fainting Warrior Mask",
		item_type		= "mask",
		spirit			= "Fainting Warrior",
		icon			= "FaintingWarrior-3.png",
		real			= "Mask10-Full.png",
		side			= "",
		price			= "15 H",
	},
	frightened_refugee_hair = {
		name			= "Frightened Refugee Hair",
		item_type		= "hair",
		spirit			= "Frightened Refugee",
		icon			= "FrightenedRefugee-2.png",
		real			= "Hair27-Puffy_Ponytail.png",
		side			= "",
		back			= "",
		price			= "3 H",
	},
	frightened_refugee_instrument = {
		name			= "Contrabass",
		alt_name		= { "Frightened Refugee Instrument", "Bass Harp" },
		item_type		= "instrument",
		spirit			= "Frightened Refugee",
		icon			= "FrightenedRefugee-3.png",
		real			= "Frightened-Refugee-Contrabass-harp.png",
		held			= "Instrument_bass_harp_playing.png",
		back			= "Instrument-Bass_Drum.png",
		price			= "5 H",
	},
	lookout_scout_instrument = {
		name			= "Horn",
		alt_name		= { "Lookout Scout Instrument" },
		item_type		= "instrument",
		spirit			= "Frightened Refugee",
		icon			= "LookoutScout-2.png",
		real			= "Lookout-Scout-Horn.png",
		held			= "Instrument_horn_playing.png",
		back			= "Instrument-Horn.png",
		price			= "5 H",
	},
	lookout_scout_facepiece = {
		name			= "Lookout Scout Face Accessory",
		item_type		= "facepiece",
		spirit			= "Frightened Refugee",
		icon			= "LookoutScout-3.png",
		real			= "Mask11.png",
		side			= "",
		price			= "10 H",
	},
	saluting_captain_hair = {
		name			= "Saluting Captain Hair",
		item_type		= "hair",
		spirit			= "Saluting Captain",
		icon			= "SalutingCaptain-2.png",
		real			= "Hair15-Short_Boy.png",
		side			= "",
		back			= "",
		price			= "5 H",
	},
	saluting_captain_prop = {
		name			= "Fireworks Staff",
		alt_name		= { "Saluting Captain Prop" },
		item_type		= "prop",
		spirit			= "Saluting Captain",
		icon			= "SalutingCaptain-3.png",
		real			= "Instrument_firework_staff_in_hand.png", -- TODO
		held			= "Instrument_firework_staff_in_hand.png",
		back			= "Instrument-Fireworks_Staff.png",
		price			= "20 H",
	},
	stealthy_survivor_cape = {
		name			= "Stealthy Survivor Cape",
		item_type		= "cape",
		spirit			= "Stealthy Survivor",
		icon			= "StealthySurvivor-3-Morybel-0146.png",
		real			= "Cape_black_2.png",
		front			= "Cape-Black.png",
		interior		= "Cape_black_3.png",
		exterior		= "",
		price			= "50 H",
	},
	stealthy_survivor_cape_2 = {
		name			= "Stealthy Survivor Tier 2 Cape",
		item_type		= "cape_2",
		spirit			= "Stealthy Survivor",
		icon			= "icon_cape_black_tier_2.png",
		real			= "Cape_black_tier_2_back.png",
		front			= "Ascended_black_cape.PNG",
		interior		= "Cape_black_tier_2_open.png",
		exterior		= "",
		price			= "150 H",
	},
	stealthy_survivor_hair = {
		name			= "Stealthy Survivor Hair",
		item_type		= "hair",
		spirit			= "Stealthy Survivor",
		icon			= "StealthySurvivor-2.png",
		real			= "Hair33-Short_Dreads.png",
		side			= "",
		back			= "",
		price			= "5 H",
	},
	
	-- Vault 
	levitating_adept_hair = {
		name			= "Levitating Adept Hair",
		item_type		= "hair",
		spirit			= "Levitating Adept",
		icon			= "LevitatingAdept-2.png",
		real			= "Hair39-Long_Mullet.png",
		side			= "",
		back			= "",
		price			= "5 H",
	},
	levitating_adept_facepiece = {
		name			= "Levitating Adept Face Accessory",
		item_type		= "facepiece",
		spirit			= "Levitating Adept",
		icon			= "LevitatingAdept-3.png",
		real			= "Mask12-Long_Panel.png",
		side			= "",
		price			= "10 H",
	},
	meditating_monastic_hair = {
		name			= "Meditating Monastic Hair",
		item_type		= "hair",
		spirit			= "Meditating Monastic",
		icon			= "Meditating-Monastic-2.png",
		real			= "Hair16-Short_Beard.png",
		side			= "",
		back			= "",
		price			= "10 H",
	},
	meditating_monastic_prop = {
		name			= "Table",
		alt_name		= { "Meditating Monastic Prop" },
		item_type		= "prop",
		spirit			= "Meditating Monastic",
		icon			= "Meditating-Monastic-3.png",
		real			= "Instrument-Chat_Table_Chair.png",
		held			= "",
		back			= "Chat_table_on_back.png",
		price			= "30 H",
	},
	memory_whisperer_cape = {
		name			= "Memory Whisperer Cape",
		item_type		= "cape",
		spirit			= "Memory Whisperer",
		icon			= "MemoryWhisperer-3.png",
		real			= "Cape_white_2.png",
		front			= "Cape-White.png",
		interior		= "Cape_white_3.png",
		exterior		= "",
		price			= "50 H",
	},
	memory_whisperer_cape_2 = {
		name			= "Memory Whisperer Tier 2 Cape",
		item_type		= "cape_2",
		spirit			= "Memory Whisperer",
		icon			= "Icon_cape_white_tier_2.png",
		real			= "Cape_white_tier_2_back.png",
		front			= "Ascended_white_cape.PNG",
		interior		= "Cape_white_tier_2_open.png",
		exterior		= "",
		price			= "150 H",
	},
	memory_whisperer_outfit = {
		name			= "Memory Whisperer Outfit",
		item_type		= "outfit",
		spirit			= "Memory Whisperer",
		icon			= "MemoryWhisperer-2.png",
		real			= "Legs04.png",
		back			= "",
		price			= "3 H",
	},
	polite_scholar_hair = {
		name			= "Polite Scholar Hair",
		item_type		= "hair",
		spirit			= "Polite Scholar",
		icon			= "PoliteScholar-3.png",
		real			= "Hair01-Bald.png",
		side			= "",
		back			= "",
		price			= "15 H",
	},
	polite_scholar_outfit = {
		name			= "Polite Scholar Outfit",
		item_type		= "outfit",
		spirit			= "Polite Scholar",
		icon			= "PoliteScholar-2.png",
		real			= "Legs02.png",
		back			= "",
		price			= "2 H",
	},
	praying_acolyte_cape = {
		name			= "Praying Acolyte Cape",
		item_type		= "cape",
		spirit			= "Praying Acolyte",
		icon			= "PrayingAcolyte-3-Morybel-0146.png",
		real			= "Cape_blue_2.png",
		front			= "Cape-Blue.png",
		interior		= "Cape_blue_3.png",
		exterior		= "",
		price			= "25 H",
	},
	praying_acolyte_cape_2 = {
		name			= "Praying Acolyte Tier 2 Cape",
		item_type		= "cape_2",
		spirit			= "Praying Acolyte",
		icon			= "PrayingAcolyte-4.png",
		real			= "Cape_blue_tier_2_back.png",
		front			= "Cape_blue_tier_2_front.png",
		interior		= "Cape_blue_tier_2_inner.png",
		exterior		= "",
		price			= "75 H",
	},
	praying_acolyte_hair = {
		name			= "Praying Acolyte Hair",
		item_type		= "hair",
		spirit			= "Praying Acolyte",
		icon			= "PrayingAcolyte-2.png",
		real			= "Hair09-Long_One_Braid.png",
		side			= "",
		back			= "",
		price			= "5 H",
	},
	
	-- Elders
	isle_elder = {
		name			= "Elder of the Isle",
		alt_name		= { "Isle Elder" },
		elder			= "elder",
		icon			= "Constellation-isle-icon-Ray.png",
		order			= 1001,
	},
	isle_elder_hair = {
		name			= "Elder of the Isle Hair",
		alt_name		= { "Isle Elder Hair" },
		item_type		= "hair",
		elder			= "Elder of the Isle",
		icon			= "Icon_hair_elder_isle.png",
		real			= "Hair19-Isle_Elder.png",
		side			= "",
		back			= "",
		price			= "4 AC",
	},
	isle_elder_facepiece = {
		name			= "Elder of the Isle Face Accessory",
		alt_name		= { "Isle Elder Face Accessory" },
		item_type		= "hair",
		elder			= "Elder of the Isle",
		icon			= "Elder-Mask-Icon-Isle-Morybel-0146.png",
		real			= "Elder-Mask-Isle-original-Credit-Nastymold.png",
		side			= "",
		back			= "",
		price			= "125 AC",
	},
	prairie_elder = {
		name			= "Elder of the Prairie",
		alt_name		= { "Prairie Elder" },
		elder			= "elder",
		icon			= "Constellation-prairie-icon-Ray.png",
		order			= 1002,
	},
	prairie_elder_hair = {
		name			= "Elder of the Prairie Hair",
		alt_name		= { "Prairie Elder Hair" },
		item_type		= "hair",
		elder			= "Elder of the Prairie",
		icon			= "Icon_hair_elder_prairie.png",
		real			= "Hair20-Prairie_Elder.png",
		side			= "",
		back			= "",
		price			= "3 AC",
	},
	prairie_elder_facepiece = {
		name			= "Elder of the Prairie Face Accessory",
		alt_name		= { "Prairie Elder Face Accessory" },
		item_type		= "hair",
		elder			= "Elder of the Prairie",
		icon			= "Elder-Mask-Icon-Prairie-Morybel-0146.png",
		real			= "Elder-Mask-Prairie-original-Credit-Nastymold.png",
		side			= "",
		back			= "",
		price			= "75 AC",
	},
	forest_elder = {
		name			= "Elder of the Forest",
		alt_name		= { "Forest Elder" },
		elder			= "elder",
		icon			= "Constellation-forest-icon-Ray.png",
		order			= 1003,
	},
	forest_elder_hair = {
		name			= "Elder of the Forest Hair",
		alt_name		= { "Forest Elder Hair" },
		item_type		= "hair",
		elder			= "Elder of the Forest",
		icon			= "Icon_hair_elder_forest.png",
		real			= "Hair21-Forest_Elder.png",
		side			= "",
		back			= "",
		price			= "6 AC",
	},
	forest_elder_facepiece = {
		name			= "Elder of the Forest Face Accessory",
		alt_name		= { "Forest Elder Face Accessory" },
		item_type		= "hair",
		elder			= "Elder of the Forest",
		icon			= "Elder-Mask-Icon-Forest-Morybel-0146.png",
		real			= "Elder-Mask-Forest-original-Credit-Nastymold.png",
		side			= "",
		back			= "",
		price			= "250 AC",
	},
	valley_elders = {
		name			= "Elder of the Valley",
		alt_name		= { "Elders of the Valley", "Valley Elder", "Valley Elders" },
		elder			= "elder",
		icon			= "Constellation-valley-icon-Ray.png",
		order			= 1004,
	},
	valley_elders_hair = {
		name			= "Elder of the Valley Hair",
		alt_name		= { "Valley Elder Hair", "Valley Elder Hair A", "Elder of the Valley Hair A" },
		item_type		= "hair",
		elder			= "Elder of the Valley",
		icon			= "Icon_hair_elder_valley_1.png",
		real			= "Hair22-Valley_Elder_1.png",
		side			= "",
		back			= "",
		price			= "5 AC",
	},
	valley_elders_hair_b = {
		name			= "Elder of the Valley Hair B",
		alt_name		= { "Valley Elder Hair B" },
		item_type		= "hair",
		elder			= "Elder of the Valley",
		icon			= "Icon_hair_elder_valley_2.png",
		real			= "Hair23-Valley_Elder_2.png",
		side			= "",
		back			= "",
		price			= "6 AC",
	},
	wasteland_elder = {
		name			= "Elder of the Wasteland",
		alt_name		= { "Wasteland Elder" },
		elder			= "elder",
		icon			= "Constellation-wasteland-icon-Ray.png",
		order			= 1005,
	},
	wasteland_elder_hair = {
		name			= "Elder of the Wasteland Hair",
		alt_name		= { "Wasteland Elder Hair" },
		item_type		= "hair",
		elder			= "Elder of the Wasteland",
		icon			= "Icon_hair_elder_wasteland.png",
		real			= "Hair24-Wasteland_Elder.png",
		side			= "",
		back			= "",
		price			= "6 AC",
	},
	vault_elder = {
		name			= "Elder of the Vault",
		alt_name		= { "Vault Elder" },
		elder			= "elder",
		icon			= "Constellation-vault-icon-Ray.png",
		order			= 1006,
	},
	vault_elder_hair = {
		name			= "Elder of the Vault Hair",
		alt_name		= { "Vault Elder Hair" },
		item_type		= "hair",
		elder			= "Elder of the Vault",
		icon			= "Icon_hair_elder_vault.png",
		real			= "Hair25-Vault_Elder.png",
		side			= "",
		back			= "",
		price			= "5 AC",
	},
	
}
local stdData = require('Module:stdData')
-- Process data, including merging in language-specific overrides
return stdData.processData(data, 'Cosmetics')