-- <nowiki>
-- Primary data for all regular spirits and elders
-- Translations should **NOT** be added to this file -- this file should always
-- be identical across all wikis.
-- Instead, a language-specific subfile provides all translated text.
-- Only variables ending in 'name' will ever need to be translated.
local data = {
	
	-- Base / Basic / Default 
	basic_sit = {
		name			= "Sit",
		item_type		= "emote",
		icon			= "Emote-basic_sit.png",
	},
	basic_call = {
		name			= "Base Call",
		alt_name		= { "Basic Call", "Default Call", "Sky Kid Call" },
		item_type		= "call",
		icon			= "voice_basic_call.png",
	},
	basic_stance = {
		name			= "Base Stance",
		alt_name		= { "Basic Stance", "Default Stance" },
		item_type		= "stance",
		icon			= "stance_basic_stand.png",
	},
	basic_flame = {
		name			= "Flame",
		item_type		= "emote",
		icon			= "Icon_flame.png",
	},
	
	--
	-- REGULAR SPIRITS
	--
	
	-- Isle
	pointing_candlemaker = {
		name			= "Pointing Candlemaker",
		emote_name		= "Point",
		alt_name		= { "Pointing", "Pointing Pilgrim" },
		item_type		= "emote",
		realm			= "isle",
		spirit			= "Pointing Candlemaker",
		icon			= "PointingCandlemaker-1.png",
		levels			= "4",
		price_2			= "1 C",
		price_3			= "2 C",
		price_4			= "2 C",
	},
	rejecting_voyager = {
		name			= "Rejecting Voyager",
		emote_name		= "No Thanks",
		alt_name		= { "No", "Rejecting" },
		item_type		= "emote",
		realm			= "isle",
		spirit			= "Rejecting Voyager",
		icon			= "RejectingVoyager-1.png",
		levels			= "4",
		price_2			= "1 C",
		price_3			= "2 C",
		price_4			= "2 C",
	},
	ushering_stargazer = {
		name			= "Ushering Stargazer",
		emote_name		= "Come",
		alt_name		= { "Ushering", "Ushering Migrant" },
		item_type		= "emote",
		realm			= "isle",
		spirit			= "Ushering Stargazer",
		icon			= "UsheringStargazer-1.png",
		levels			= "4",
		price_2			= "1 C",
		price_3			= "2 C",
		price_4			= "2 C",
	},
	
	-- Prairie
	applauding_bellmaker = {
		name			= "Applauding Bellmaker",
		emote_name		= "Clap",
		item_type		= "emote",
		realm			= "prairie",
		spirit			= "Applauding Bellmaker",
		icon			= "ApplaudingBellmaker-1.png",
		levels			= "4",
		price_2			= "1 C",
		price_3			= "3 C",
		price_4			= "3 C",
	},
	bird_whisperer = {
		name			= "Bird Whisperer",
		emote_name		= "Bird Call",
		alt_name		= { "Bird" },
		item_type		= "call",
		realm			= "prairie",
		spirit			= "Bird Whisperer",
		icon			= "BirdWhisperer-1.png",
		levels			= "1",
	},
	butterfly_charmer = {
		name			= "Butterfly Charmer",
		emote_name		= "Butterfly",
		item_type		= "emote",
		realm			= "prairie",
		spirit			= "Butterfly Charmer",
		icon			= "ButterflyCharmer-1.png",
		levels			= "4",
		price_2			= "1 C",
		price_3			= "2 C",
		price_4			= "2 C",
	},
	ceremonial_worshiper = {
		name			= "Ceremonial Worshiper",
		emote_name		= "Teamwork",
		alt_name		= { "High Candle", "High Candle Action", "Ceremonial Worshipper" },
		item_type		= "emote",
		realm			= "prairie",
		spirit			= "Ceremonial Worshiper",
		icon			= "CeremonialWorshiper-1.png",
		levels			= "1",
	},
	exhausted_dock_worker = {
		name			= "Exhausted Dock Worker",
		emote_name		= "Wipe Brow",
		item_type		= "emote",
		realm			= "prairie",
		spirit			= "Exhausted Dock Worker",
		icon			= "ExhaustedDockWorker-1.png",
		levels			= "4",
		price_2			= "1 C",
		price_3			= "5 C",
		price_4			= "5 C",
	},
	laughing_light_catcher = {
		name			= "Laughing Light Catcher",
		emote_name		= "Laugh",
		item_type		= "emote",
		realm			= "prairie",
		spirit			= "Laughing Light Catcher",
		icon			= "LaughingLightCatcher-1.png",
		levels			= "4",
		price_2			= "1 C",
		price_3			= "5 C",
		price_4			= "5 C",
	},
	slumbering_shipwright = {
		name			= "Slumbering Shipwright",
		emote_name		= "Yawn",
		item_type		= "emote",
		realm			= "prairie",
		spirit			= "Slumbering Shipwright",
		icon			= "SlumberingShipwright-1.png",
		levels			= "4",
		price_2			= "1 C",
		price_3			= "2 C",
		price_4			= "2 C",
	},
	waving_bellmaker = {
		name			= "Waving Bellmaker",
		emote_name		= "Wave",
		item_type		= "emote",
		realm			= "prairie",
		spirit			= "Waving Bellmaker",
		icon			= "WavingBellmaker-1.png",
		levels			= "6",
		price_2			= "1 C",
		price_3			= "2 C",
		price_4			= "2 C",
		price_5			= "3 C",
		price_6			= "3 C",
	},
	
	-- Forest
	apologetic_lumberjack = {
		name			= "Apologetic Lumberjack",
		emote_name		= "Apologize",
		alt_name		= { "Deep Bow", "Apology" },
		item_type		= "emote",
		realm			= "forest",
		spirit			= "Apologetic Lumberjack",
		icon			= "ApologeticLumberjack-1.png",
		levels			= "4",
		price_2			= "3 C",
		price_3			= "3 C",
		price_4			= "3 C",
	},
	blushing_prospector = {
		name			= "Blushing Prospector",
		emote_name		= "Shy",
		alt_name		= { "Blush" },
		item_type		= "emote",
		realm			= "forest",
		spirit			= "Blushing Prospector",
		icon			= "BlushingProspector-1.png",
		levels			= "4",
		price_2			= "3 C",
		price_3			= "4 C",
		price_4			= "4 C",
	},
	dismayed_hunter = {
		name			= "Dismayed Hunter",
		emote_name		= "Shocked",
		alt_name		= { "Hands To Head", "Dismay" },
		item_type		= "emote",
		realm			= "forest",
		spirit			= "Dismayed Hunter",
		icon			= "DismayedHunter-1.png",
		levels			= "4",
		price_2			= "3 C",
		price_3			= "5 C",
		price_4			= "5 C",
	},
	hidenseek_pioneer = {
		name			= "Hide'n'Seek Pioneer",
		emote_name		= "Hide and Seek",
		alt_name		= { "Hide'n'Seek", "Hide and Seek Action" },
		item_type		= "emote",
		realm			= "forest",
		spirit			= "Hide'n'Seek Pioneer",
		icon			= "HideNSeekPioneer-1.png",
		levels			= "1",
	},
	pouty_porter = {
		name			= "Pouty Porter",
		emote_name		= "Angry",
		alt_name		= { "Pout" },
		item_type		= "emote",
		realm			= "forest",
		spirit			= "Pouty Porter",
		icon			= "PoutyPorter-1.png",
		levels			= "4",
		price_2			= "3 C",
		price_3			= "4 C",
		price_4			= "4 C",
	},
	shivering_trailblazer = {
		name			= "Shivering Trailblazer",
		emote_name		= "Shiver",
		item_type		= "emote",
		realm			= "forest",
		spirit			= "Shivering Trailblazer",
		icon			= "ShiveringTrailblazer-1.png",
		levels			= "4",
		price_2			= "2 C",
		price_3			= "3 C",
		price_4			= "3 C",
	},
	tearful_light_miner = {
		name			= "Tearful Light Miner",
		emote_name		= "Crying",
		alt_name		= { "Tears" },
		item_type		= "emote",
		realm			= "forest",
		spirit			= "Tearful Light Miner",
		icon			= "TearfulLightMiner-1.png",
		levels			= "6",
		price_2			= "3 C",
		price_3			= "4 C",
		price_4			= "4 C",
		price_5			= "5 C",
		price_6			= "5 C",
	},
	whale_whisperer = {
		name			= "Whale Whisperer",
		emote_name		= "Whale Call",
		alt_name		= { "Whale" },
		item_type		= "call",
		realm			= "forest",
		spirit			= "Whale Whisperer",
		icon			= "WhaleWhisperer-1.png",
		levels			= "1",
	},
	
	-- Valley
	backflipping_champion = {
		name			= "Backflipping Champion",
		emote_name		= "Backflip",
		item_type		= "emote",
		realm			= "valley",
		spirit			= "Backflipping Champion",
		icon			= "BackflippingChampion-1.png",
		price			= "",
	},
	bowing_medalist = {
		name			= "Bowing Medalist",
		emote_name		= "Bow",
		item_type		= "emote",
		realm			= "valley",
		spirit			= "Bowing Medalist",
		icon			= "BowingMedalist-1.png",
		price			= "",
	},
	cheerful_spectator = {
		name			= "Cheerful Spectator",
		emote_name		= "Cheer",
		item_type		= "emote",
		realm			= "valley",
		spirit			= "Cheerful Spectator",
		icon			= "CheerfulSpectator-1.png",
		price			= "",
	},
	confident_sightseer = {
		name			= "Confident Sightseer",
		emote_name		= "Confident Stance",
		alt_name		= { "Confident" },
		item_type		= "stance",
		realm			= "valley",
		spirit			= "Confident Sightseer",
		icon			= "ConfidentSightseer-1.png",
		price			= "",
	},
	handstanding_thrillseeker = {
		name			= "Handstanding Thrillseeker",
		emote_name		= "Handstand",
		item_type		= "emote",
		realm			= "valley",
		spirit			= "Handstanding Thrillseeker",
		icon			= "HandstandingThrillseeker-1.png",
		price			= "",
	},
	manta_whisperer = {
		name			= "Manta Whisperer",
		emote_name		= "Manta Call",
		alt_name		= { "Manta" },
		item_type		= "call",
		realm			= "valley",
		spirit			= "Manta Whisperer",
		icon			= "MantaWhisperer-1.png",
		price			= "",
	},
	proud_victor = {
		name			= "Proud Victor",
		emote_name		= "Proud Stance",
		alt_name		= { "Proud" },
		item_type		= "stance",
		realm			= "valley",
		spirit			= "Proud Victor",
		icon			= "ProudVictor-1.png",
		price			= "",
	},
	
	-- Wasteland
	courageous_soldier = {
		name			= "Courageous Soldier",
		emote_name		= "Courageous Stance",
		alt_name		= { "Courageous" },
		item_type		= "stance",
		realm			= "wasteland",
		spirit			= "Courageous Soldier",
		icon			= "CourageousSoldier-1.png",
		price			= "",
	},
	fainting_warrior = {
		name			= "Fainting Warrior",
		emote_name		= "Faint",
		alt_name		= { "Fall Down" },
		item_type		= "emote",
		realm			= "wasteland",
		spirit			= "Fainting Warrior",
		icon			= "FaintingWarrior-1.png",
		price			= "",
	},
	frightened_refugee = {
		name			= "Frightened Refugee",
		emote_name		= "Duck",
		alt_name		= { "Frightened" },
		item_type		= "emote",
		realm			= "wasteland",
		spirit			= "Frightened Refugee",
		icon			= "FrightenedRefugee-1.png",
		price			= "",
	},
	lookout_scout = {
		name			= "Lookout Scout",
		emote_name		= "Look Around",
		alt_name		= { "Lookout" },
		item_type		= "emote",
		realm			= "wasteland",
		spirit			= "Frightened Refugee",
		icon			= "LookoutScout-1.png",
		price			= "",
	},
	saluting_captain = {
		name			= "Saluting Captain",
		emote_name		= "Salute",
		item_type		= "emote",
		realm			= "wasteland",
		spirit			= "Saluting Captain",
		icon			= "SalutingCaptain-1.png",
		price			= "",
	},
	stealthy_survivor = {
		name			= "Stealthy Survivor",
		emote_name		= "Sneaky Stance",
		alt_name		= { "Sneaky", "Stealthy", "Stealthy Stance" },
		item_type		= "stance",
		realm			= "wasteland",
		spirit			= "Stealthy Survivor",
		icon			= "StealthySurvivor-1.png",
		price			= "",
	},
	
	-- Vault 
	levitating_adept = {
		name			= "Levitating Adept",
		emote_name		= "Telekinesis",
		item_type		= "emote",
		realm			= "vault",
		spirit			= "Levitating Adept",
		icon			= "LevitatingAdept-1.png",
		price			= "",
	},
	meditating_monastic = {
		name			= "Meditating Monastic",
		emote_name		= "Float",
		alt_name		= { "Meditate" },
		item_type		= "",
		realm			= "vault",
		spirit			= "Meditating Monastic",
		icon			= "Meditating-Monastic-1.png",
		price			= "",
	},
	memory_whisperer = {
		name			= "Memory Whisperer",
		emote_name		= "Cosmic Manta Call",
		alt_name		= { "Cosmic Manta" },
		item_type		= "call",
		realm			= "vault",
		spirit			= "Memory Whisperer",
		icon			= "MemoryWhisperer-1.png",
		price			= "",
	},
	polite_scholar = {
		name			= "Polite Scholar",
		emote_name		= "Polite Stance",
		alt_name		= { "Polite" },
		item_type		= "stance",
		realm			= "vault",
		spirit			= "Polite Scholar",
		icon			= "PoliteScholar-1.png",
		price			= "",
	},
	praying_acolyte = {
		name			= "Praying Acolyte",
		emote_name		= "Pray",
		item_type		= "emote",
		realm			= "vault",
		spirit			= "Praying Acolyte",
		icon			= "PrayingAcolyte-1.png",
		price			= "",
	},
	
	
	--
	-- Gratitude
	--
	sassy_drifter = {
		name			= "Sassy Drifter",
		emote_name		= "Sassy Stance",
		alt_name		= { "Sassy" },
		item_type		= "emote",
		season			= "gratitude",
		spirit			= "Sassy Drifter",
		icon			= "Mimi-4117_02_sassy_drifter_emote.png",
		s_price			= "free",
		price			= "free",
	},
	stretching_guru = {
		name			= "Stretching Guru",
		emote_name		= "Yoga",
		item_type		= "emote",
		season			= "gratitude",
		spirit			= "Stretching Guru",
		icon			= "Mimi-4117_02_stretching_guru_emote.png",
		s_price_1		= "free",
		price			= "",
	},
	
}
local stdData = require('Module:stdData')
-- Process data, including merging in language-specific overrides
return stdData.processData(data, 'Emotes')