-- <nowiki>
-- Primary data for all seasons
-- Translations should **NOT** be added to this file -- this file should always
-- be identical across all wikis.
-- Instead, a language-specific subfile provides all translated text.
-- Only variables ending in 'name' will ever need to be translated.
local data = {
    gratitude = {
        name               = "Season of Gratitude",
        guide_name         = "Gratitude Guide",
        guide_link         = "Gratitude Guide",
        short_name         = "Gratitude",
        icon               = "1_Gratitude.png",
        sort               = 1,
        mask_u             = "Icon_mask_gratitude_ult_deer.png",
        mask_u_real        = "Mask20-Seasonal_SoG_2019.png",
        necklace_u_real    = "Gratitude_pendant.png",
        sh_icon            = "Gratitude-heart-Ray.png",
        sc_icon            = "Gratitude-candle-Ray.png",
    },
    lightseekers = {
        name               = "Season of Lightseekers",
        guide_name         = "Lightseeker Guide",
        guide_link         = "Lightseeker Guide",
        alt_name           = { "Lightseekers Guide" },
        short_name         = "Lightseekers",
        icon               = "2_Lightseekers.png",
        sort               = 2,
        prop_u             = "Icon_prop_lightseekers_large_umbrella.png",
        prop_u_real        = "Lightseekers-Ultimate-Umbrella-Prop.png ",
        prop_u_held		   = "Lightseekers_ultimate_umbrella_v2.png",
        prop_u_back		   = "Lightseekers instrument ult umbrella on back v2.png",
        prop_u_name        = "Lightseekers Ultimate Bioluminescent Umbrella",
        necklace_u_real    = "Lightseekers_pendant.png",
        sh_icon            = "Lightseekers-heart-Ray.png",
        sc_icon            = "Lightseekers-candle-Ray.png",
    },
    belonging = {
        name               = "Season of Belonging",
        guide_name         = "Belonging Guide",
        guide_link         = "Belonging Guide",
        short_name         = "Belonging",
        icon               = "3_Belonging.png",
        sort               = 3,
        prop_u             = "Icon_prop_belonging_bonfire.png",
        prop_u_real        = "Season_of_belonging_ultimate_bonfire.png",
        prop_u_back		   = "Belonging-Ultimate-Prop-on-Back.png",
        prop_u_name        = "Belonging Ultimate Bonfire",
        necklace_u_real    = "Season_of_belonging_pendant.png",
        sh_icon            = "Belonging-heart-Ray.png",
        sc_icon            = "Belonging-candle-Ray.png",
    },
    rhythm = {
        name               = "Season of Rhythm",
        guide_name         = "Rhythm Guide",
        guide_link         = "Rhythm Guide",
        short_name         = "Rhythm",
        icon               = "4_Rhythm.png",
        sort               = 4,
        hair_u             = "Icon_hair_rhythm_ultimate.png",
        hair_u_real        = "Season_of_rhythm_hair_ultimate_v2.png",
        mask_u             = "Icon_mask_rhythm_ult.png",
        mask_u_real        = "Season_of_rhythm_mask_ultimate_v2.png",
        necklace_u_real    = "Season_of_rhythm_pendant_v2.png",
        sh_icon            = "Rhythm-heart-Ray.png",
        sc_icon            = "Rhythm-candle-Ray.png",
    },
    enchantment = {
        name               = "Season of Enchantment",
        guide_name         = "Enchantment Guide",
        guide_link         = "Enchantment Guide",
        short_name         = "Enchantment",
        icon               = "5_Enchantment.png",
        sort               = 5,
        hair_u             = "Icon_hair_enchantment_ultimate.png",
        hair_u_real        = "Season_of_enchantment_hair_ultimate_v2.png",
        headpiece_u        = "Icon_hair_enchantment_ultimate_tassles.png",
        headpiece_u_real   = "Season_of_enchantment_ultimate_tassels_v2.png",
        necklace_u_real    = "Season_of_enchantment_pendant_v2.png",
        sh_icon            = "Enchantment-heart-Ray.png",
        sc_icon            = "Enchantment-candle-Ray.png",
    },
    sanctuary = {
        name               = "Season of Sanctuary",
        guide_name         = "Sanctuary Guide",
        guide_link         = "Sanctuary Guide",
        short_name         = "Sanctuary",
        inst_name          = "Sanctuary Handpan",
        icon               = "6_Sanctuary.png",
        sort               = 6,
        cape_u             = "Icon_cape_sanctuary_manta-Morybel-0146.png",
        cape_u_real        = "Season of sanctuary cape ultimate back v2.png",
        cape_u_front       = "Season of sanctuary cape ultimate front v2.png",
        cape_u_interior    = "Season of sanctuary cape ultimate open v2.png",
        cape_u_exterior    = "Season-of-Sanctuary-Ultimate-Cape-back-exterior.png",		
        instrument_u       = "Icon_instrument_sanctuary_hand_pan.png",
        instrument_u_real  = "Sanctuary-Handpan-ultimate.png",
        necklace_u_real    = "Season_of_sanctuary_sanctuary_pendant_v2.png",
        sh_icon            = "Sanctuary-heart-Ray.png",
        sc_icon            = "Sanctuary-Seasonal-candle-icon-Morybel-0146.png",
    },
    prophecy    = {
        name               = "Season of Prophecy",
        guide_name         = "Prophecy Guide",
        guide_link         = "Prophecy Guide",
        short_name         = "Prophecy",
        inst_name          = "Prophecy Drum",
    	alt_name           = { "Dundun" },
        icon               = "7_Prophecy.png",
        sort               = 7,
        instrument_u       = "Icon_instrument_prophecy_drum.png",
        instrument_u_real  = "Prophecy-ultimate-_drum.png",
        mask_u             = "Icon_mask_prophecy_ult.png",
        mask_u_real        = "Prophecy-Guide_Mask.png",
        necklace_u_real    = "Prophecy_pendant_v2.png",
        sh_icon            = "Prophecy-heart-Ray.png",
        sc_icon            = "Prophecy-candle-Ray.png",
    },
    dreams = {
        name               = "Season of Dreams",
        guide_name         = "Dreams Guide",
        guide_link         = "Dreams Guide",
        short_name         = "Dreams",
        icon               = "8_Dreams.png",
        sort               = 8,
        cape_u             = "Icon_cape_dreams_ultimate-Morybel-0146.png",
        cape_u_real        = "Dreams_cape_ultimate_back_v2.png",
        cape_u_front       = "Dreams cape ultimate front v2.png",
        cape_u_interior    = "Dreams cape ultimate open v2.png",
        cape_u_exterior    = "Season-of-Dreams-Ultimate-Cape-back-exterior.png",
        mask_u             = "Icon_mask_dreams_ult.png",
        mask_u_real        = "Dreams_mask_ultimate_v2.png",
        necklace_u_real    = "Dreams_pendant_v2.png",
        sh_icon            = "Dreams-heart-Ray.png",
        sc_icon            = "Dreams-candle-Ray.png",
    },
    assembly = {
        name               = "Season of Assembly",
        guide_name         = "Assembly Guide",
        guide_link         = "Assembly Guide",
        short_name         = "Assembly",
        inst_name          = "Bugle",
        icon               = "9_Assembly.png",
        sort               = 9,
        cape_u             = "Icon_cape_assembly_ultimate-Morybel-0146.png",
        cape_u_real        = "Assembly_cape_ultimate_back_v2.png",
        cape_u_front       = "Assembly cape ultimate front v2.png",
        cape_u_interior    = "Assembly cape ultimate open v2.png",
        cape_u_exterior    = "Season-of-Assembly-Ultimate-Cape-back-exterior.png",		
        hair_u             = "Icon_hair_assembly_ultimate.png",
        hair_u_real        = "Assembly_hair_ultimate_v2.png",
        instrument_u       = "Icon_instrument_assembly_bugle.png",
        instrument_u_real  = "Assembly-ultimate-Buggle.png",
        mask_u             = "Icon_mask_assembly_ult.png",
        mask_u_real        = "Assembly_mask_ultimate_v2.png",
        necklace_u_real    = "Assembly_pendant_v2.png",
		--[=[
		Trying to use letters that represent the item names, but need to choose
		item names carefully to not have duplicate letters.  So letters are:
		  p = pillow
		  j = jar
		  l = light
		  b = bookcase
		  t = tent
		]=]
        prop_p             = "Icon_prop_assembly_pillow.png",
        prop_p_real        = "Prop_forest_treehouse_pillow.png",
		prop_p_name        = "Pillow",
        prop_j             = "Icon_prop_pot.png",
        prop_j_real        = "Assembly_prop_pot_down.png",
        prop_j_name        = "Jar",
        prop_l             = "Icon_prop_assembly_brazier.png",
        prop_l_real        = "Prop_forest_treehouse_brazier.png",
        prop_l_name        = "Small Brazier",
        prop_b             = "Icon_prop_bookcase.png",
        prop_b_real        = "Assembly_prop_bookcase_2.png",
        prop_b_name        = "Bookcase",
        prop_t             = "Icon_prop_assembly_tent.png",
        prop_t_real        = "Prop_forest_treehouse_tent.png",
        prop_t_name        = "Tent",
        sh_icon            = "Assembly Heart.png",
        sc_icon            = "Assembly-candle-Ray.png",
    },
    the_little_prince = {
    	--[=[
		i for iap
		
		s for scarf
		a for asteroid jacket
		]=]
        name               = "Season of The Little Prince",
        guide_name         = "The Rose",
        guide_link         = "The Rose",
		short_name         = "Little Prince",
        alt_name           = { "Rose", "The Rose Guide", "Prince", "The Little Prince" },
        icon               = "10_Little_Prince.png",
        sort               = 10,
        hair_u             = "Icon_hair_prince_ultimate.png",
        hair_u_real        = "Season_of_little_prince_hair6_ultimate.PNG",
        outfit_u           = "Icon_pants_prince_pjs.png",
        outfit_u_real      = "Season_of_little_prince_pants3_iap_pj.PNG",
        outfit_u_back	   = "The-Little-Prince-Ultimate-Outfit-Back.png",
        prop_u             = "Icon_prop_little_prince_rose.png",
        prop_u_real        = "Season_of_little_prince_inst2rose_ultimate.PNG",
        prop_u_name        = "Little Prince Ultimate Rose Musicbox",
        prop_i             = "Icon_prop_little_prince_fox.png",
        prop_i_real        = "Season_of_little_prince_iap_fox_inst.png",
        prop_i_spell       = "SOTLP-Fox-Backpack-Spells.png",
        prop_i_name        = "Little Prince Fox",
        outfit_i           = "Icon_pants_prince_sword.png",
        outfit_i_real      = "Season_of_little_prince_pants2_iap_sword.PNG",
        outfit_i_spell      = "SOTLP-Prince-Sword-Suit-Spells.png",
        outfit_i_back	   = "The-Little-Prince-Sword-Suit-Outfit-Back.png",
        cape_s             = "Icon_cape_littleprince_scarf-Morybel-0146.png",
        cape_s_real        = "Season_of_little_prince_cape7_iap_scarf.png",
        cape_s_spell       = "SOTLP-scarf-Cape-Spells.png",
        cape_s_front       = "Little prince scarf front.png",
        cape_s_interior    = "",
        cape_s_exterior    = "",
        cape_a             = "Icon_cape_littleprince_asteroid-Morybel-0146.png",
        cape_a_real        = "Little_prince_asteroid_cape_back.png",
        cape_a_spell       = "SOTLP-Green-Cape-Spells.png",
        cape_a_front       = "Season of little prince cape5.PNG",
        cape_a_interior    = "Little prince asteroid cape inner.png",
        cape_a_exterior    = "Little-Prince-Asteroid-Jacket-back-exterior.png",
        necklace_u_real    = "Little_prince_pendant.png",
        sh_icon            = "Little Prince Heart.png",
        sc_icon            = "Little-prince-candle-Ray.png",
    },
    flight = {
        name               = "Season of Flight",
        guide_name         = "Flight Guide",
        guide_link         = "Flight Guide",
        short_name         = "Flight",
        icon               = "11_Flight.png",
        sort               = 11,
        hairpiece_u        = "Icon_season_of_flight_headpiece_4_ult.png",
        hairpiece_u_real   = "Season_of_flight_headpiece_4_ult.png",
        outfit_u           = "Icon_season_of_flight_pants_1_ult.png",
        outfit_u_real      = "Season_of_flight_pants_1_ult.png",
        outfit_u_back	   = "Flight-Ultimate-Outfit-Back.png",
        necklace_u_real    = "Season_of_flight_pendant.png",
        sh_icon            = "Season Of Flight Heart.png",
        sc_icon            = "Flight-candle-Ray.png ",
    },
    abyss = {
        name               = "Season of Abyss",
        guide_name         = "Abyss Guide",
        guide_link         = "Abyss Guide",
        short_name         = "Abyss",
        icon               = "12_Abyss.png",
        sort               = 12,
        mask               = "SOAbyss-additional-mask-Morybel-0146.png",
        mask_real          = "SOAbyss-mask2.png",
        mask_u             = "SOAbyss-Ultime-gift-underwater-mask.png",
        mask_u_real        = "SOAbyss-Ultime-gift-underwater-mask-screenshot.png",
        cape_u             = "SOAbyss-Ultime-gift-Cape-vector.png",
        cape_u_real        = "SOAbyss-Ultime-gift-Cape-back.png",
        cape_u_front       = "SOAbyss-Ultime-gift-Cape-front.png",
        cape_u_interior    = "SOAbyss-Ultime-gift-Cape-front-butterfly.png",
        cape_u_exterior    = "",
        headpiece_u        = "SOAbyss-Ultime-gift-hair-tassle.png",
        headpiece_u_real   = "SOAbyss-Ultime-gift-hair-tassle-screenshot.png",
        necklace_u_real    = "SOAbyss-Pendant.png",
        sh_icon            = "SOAbyss-seasonal-heart.png",
        sc_icon            = "Abyss-candle-Ray.png ",
    },
    performance = {
        name               = "Season of Performance",
        guide_name         = "Performance Guide",
        -- Setting guide_link means that this exists as a non-redirect spirit page
        guide_link         = "Performance Guide",
        short_name         = "Performance",
        icon               = "13_SOPerformance_logo.png",
        sort               = 13,
        hair_u             = "SOPerformance-ultimate-hair-icon.png",
        hair_u_real        = "SOPerformance-ultimate-hair.png",
        cape_u             = "SOPerformance-ultimate-cape-icon.png",
        cape_u_real        = "SOPerformance-ultimate-cape-back.png",
        cape_u_front       = "SOPerformance-ultimate-cape-front.png",
        cape_u_interior    = "SOPerformance-ultimate-cape-front-butterfly.png",
        cape_u_exterior	   = "",
        mask_u             = "SOPerformance-ultimate-mask-icon.png",
        mask_u_real        = "SOP-Ultimate-guide-mask.png",
        mask               = "Morybel-0146-SOPerformance-ultimate-mask-icon-f2p.png",
        mask_real          = "SOPerformance-ultimate-mask-f2p.png",
        prop               = "SOPerformance-flower-pot-icon-Morybel-0146.png",
        prop_real          = "SOPerformance-flower-pot.png",
        prop_name          = "Flower Pot",
        necklace_u_real    = "SOPerformance-pendant.png",
        sh_icon            = "SOPerformance-seasonal-heart-icon-Morybel-0146.png",
        sc_icon            = "Performance-candle-Ray.png",
    },
    shattering = {
        name               = "Season of Shattering",
        guide_name         = "The Void of Shattering",
        guide_link         = "The Void of Shattering",
		short_name         = "Shattering",
        alt_name           = { "Void of Shattering", "Shattering Guide" },
        icon               = "14_SOShattering.png",
        sort               = 14,
		--[=[
		I'm opting to NOT use the _u suffix because there are two ultimate capes.
		Instead, just do explicit links/labels for these capes
		]=]
        cape_k             = "SOShattering-ultimate-Cape-krill-Icon-Morybel-0146.png",
        cape_k_real        = "SOShattering-ultimate-Cape-krill-back.png",
        cape_k_front       = "SOShattering-ultimate-Cape-krill-front.png",
        cape_k_interior    = "SOShattering-ultimate-Cape-krill-front-butterfly.png",
        cape_k_exterior    = "",
        cape_m             = "SOShattering-ultimate-Cape-manta-Icon-Morybel-0146.png",
        cape_m_real        = "SOShattering-ultimate-Cape-manta-bac.png",
        cape_m_front       = "SOShattering-ultimate-Cape-manta-front.png",
        cape_m_interior    = "SOShattering-ultimate-Cape-manta-front-butterly.png",
        cape_m_exterior    = "",
        necklace_u_real    = "SOShattering-pendant.png",
        sh_icon            = "SOShattering-Seasonal-heart-Morybel-0146.png",
        sc_icon            = "SOShattering-Seasonal-candle-Morybel-0146.png",
    },
    aurora = {
		--[=[
		i for iap
		c for clap
		k for conduct
		s for skipping
		
		
		g for giving in cape
		w for wings of aurora
		t for to the love 
		e for Encore concert
		]=]
        name               = "Season of AURORA",
        guide_name         = "AURORA Guide",
        guide_link         = "AURORA Guide",
        short_name         = "AURORA",
        -- inst_name          = "Voice of AURORA",
        icon               = "15-Aurora.png",
        sort               = 15,
        hair_u             = "SoAurora-Ultimate-Hair-icon-Morybel-0146.png",
        hair_u_real        = "SoAurora-Ultimate-Hair.png",
        cape_u             = "SoAurora-Ultimate-Cape-icon-Morybel-0146.png",
        cape_u_real        = "SoAurora-Ultimate-Cape-back.png",
        cape_u_front       = "SoAurora-Ultimate-Cape-front.png",
        cape_u_interior    = "SoAurora-Ultimate-Cape-front-butterly.png",
        cape_u_exterior    = "",
        outfit_u           = "SoAurora-Ultimate-Outfit-icon-Morybel-0146.png",
        outfit_u_real      = "SoAurora-Ultimate-Outfit.png",
        outfit_u_back	   = "SoAurora-Ultimate-Outfit-back.png",
        mask               = "SoAurora-Additional-Mask-Icon-Morybel-0146.png",
        mask_name          = "Cure For Me Mask",
        mask_real          = "SoAURORA-Cure-for-me-Mask.png",
        outfit             = "SoAurora-Additional-Green-Outfit-Icon-Morybel-0146.png",
        outfit_name        = "Cure For Me Outfit",
        outfit_real        = "SoAurora-Cure-for-me-Outfit-front.png",
        outfit_back        = "SoAurora-Cure-for-me-Outfit-back.png",
        emote_c            = "SoAurora-Ultimate-Expression-Dance-1-Icon-Morybel-0146.png",
        emote_c_name       = "Silent Clap",
        emote_k            = "SoAurora-Ultimate-Expression-Dance-2-Icon-Morybel-0146.png",
        emote_k_name       = "Conduct",
        emote_s            = "SoAurora-Ultimate-Expression-Dance-3-Icon-Morybel-0146.png",
        emote_s_name       = "Skipping",
        headpiece_i        = "Aurora-Hair-Accessory-icon-Morybel-0146.png",
        headpiece_i_name   = "Tiara We Can Touch",
        headpiece_i_real   = "SoAurora-Hair-Accessory-no-hair.png",
        hair_i             = "Aurora-Runaway-Hair-Morybel-0146.png",
        hair_i_name        = "Runaway Hair",
        hair_i_real        = "SoAurora-Short-bang-hairstyle.png",
        outfit_i           = "Aurora-Runaway-outfit-Morybel-0146.png",
        outfit_i_name      = "Runaway Outfit",
        outfit_i_real      = "SoAurora-Purple-Outfit.png",
        outfit_i_back      = "Runaway-Outfit-back.png",
        outfit_t           = "SoAurora-To-The-Love-Outfit-Icon-Morybel-0146.png",
        outfit_t_name      = "To The Love Outfit",
        outfit_t_real      = "SoAurora-To-The-Love-Outfit-front.png",
        outfit_t_back      = "SoAurora-To-The-Love-Outfit-back.png",
        -- instrument         = "Aurora-Voice-of-Aurora-Icon-Morybel-0146-.png",
        -- instrument_real    = "Aurora-Voice-of-Aurora-Instrument.png",
        cape_g             = "SoAurora-Giving-In-Cape-IAP-Icon-Morybel-0146.png",
        cape_g_name        = "Giving In Cape",
        cape_g_real        = "SoAurora-Giving-In-Cape-IAP-Cape-back.png",
        cape_g_front       = "SoAurora-Giving-In-Cape-IAP-Cape-front.png",
        cape_g_interior    = "SoAurora-Giving-In-Cape-IAP-Cape-front-butterfly.png",
        cape_g_exterior    = "SoAurora-Giving-In-Cape-IAP-Cape-back-butterfly.png",
        cape_w             = "SoAURORA-Wings-of-AURORA-Cape-Icon-Morybel-0146.png",
        cape_w_name        = "Wings of AURORA",
        cape_w_real        = "SoAURORA-Wings-of-AURORA-Cape-back.png",
        cape_w_front       = "SoAURORA-Wings-of-AURORA-Cape-front.png",
        cape_w_interior    = "SoAURORA-Wings-of-AURORA-Cape-font-butterfly.png",
        cape_w_exterior    = "SoAURORA-Wings-of-AURORA-Cape-back-butterfly.png",
        necklace_u_real    = "SoAurora-Seasonal-Pass-pendant.png",
        sh_icon            = "SoAurora-Seasonal-Heart-Morybel-0146.png",
        sc_icon            = "SoAurora-Seasonal-Candle-Morybel-0146.png",
        --cure for me expression introduced during the Encore concert
        emote_e            = "AURORA-Cure-for-Me-expression-icon-Credit-Morybel.png",
        emote_e_name       = "Cure for Me Dance",
    },    
	remembrance = {
			--[=[
		p for plants
		k for kettle
		c for chimes
		m for manta
		q for crabs - since c and k are already in use
		]=]
        name               = "Season of Remembrance",
        guide_name         = "Remembrance Guide",
        -- Setting guide_link means that this exists as a non-redirect spirit page
        guide_link         = "Remembrance Guide",
        short_name         = "Remembrance",
        icon               = "16_SORemembrance_logo.png",
        sort               = 16,
		neckpiece_u        = "SoRemembrance-Ultimate-Gift-Sash-Icon-Morybel-0146.png",
		neckpiece_u_real   = "SoRemembrance-Ultimate-Gift-Sash.png",
		prop_u			   = "SoRemembrance-Ultimate-Gift-Manta-Projector-Morybel-0146.png",
		prop_u_real        = "SoRemembrance-Ultimate-Gift-Manta-Projector.png",
		prop_u_name        = "Remembrance Ultimate Manta Projector",
        prop_p             = "SoRemembrance-Prop-Plants-Morybel-0146.png",
        prop_p_real        = "SoRemembrance-Prop-Plants.png",
        prop_p_name        = "Potted Plant",
        prop_k             = "SoRemembrance-Prop-Kettle-Morybel-0146.png",
        prop_k_real        = "SoRemembrance-Prop-Kettle.png",
        prop_k_name        = "Kettle",
        prop_c             = "SoRemembrance-Prop-Chimes-Morybel-0146.png",
        prop_c_real        = "SoRemembrance-Prop-Chimes.png",
        prop_c_name        = "Chimes",
        prop_m             = "SoRemembrance-Prop-Manta-Plush-icon-Morybel-0146.png",   
        prop_m_real        = "Remembrance-Prop-Manta-Plush.png",
        prop_m_back		   = "Remembrance-Prop-Manta-Plush-Item-on-back.png",
        prop_m_held		   = "Remembrance-Prop-Manta-Plush-Held.png",
        prop_m_name		   = "Manta Plush",
        prop_q             = "SoRemembrance-Prop-Crab-Plush-icon-Morybel-0146.png",
        prop_q_real        = "Remembrance-Prop-Crab-Plush.png",
        prop_q_held		   = "Remembrance-Prop-Crab-Plush-Held.png",
        prop_q_back		   = "Remembrance-Prop-Crab-Plush-Item-on-back.png",
        prop_q_name		   = "Crab Plush",
        necklace_u_real    = "SoRemembrance-Seasonal-Pass-pendant.png",
        sh_icon            = "SORemembrance-seasonal-heart-icon-Morybel-0146.png",
        sc_icon            = "SORemembrance-seasonal-candle-icon-Morybel-0146.png",
    },    
    passage = {
        name               = "Season of Passage",
        guide_name         = "Passage Guide",
        -- Setting guide_link means that this exists as a non-redirect spirit page
        guide_link         = "Passage Guide",
        short_name         = "Passage",
        icon               = "17_SOPassage_logo.png",
        sort               = 17,
        cape_u             = "Passage-Ultimate-Guide-Cape-icon-Morybel-0146.png",
        cape_u_real        = "Passage-Ultimate-Guide-Cape-back.png",
        cape_u_front       = "Passage-Ultimate-Guide-Cape-front.png",
        cape_u_interior    = "Passage-Ultimate-Guide-Cape-front-butterfly.png",
        cape_u_exterior    = "Passage-Ultimate-Guide-Cape-back-butterfly.png",
        mask_u             = "Passage-Ultimate-Guide-Mask-icon-Morybel-0146.png",
        mask_u_real        = "Passage-Ultimate-Guide-Mask.png",
        mask_b             = "Passage-additional-mask-Boar-icon-Morybel-0146.png",
        mask_b_real        = "Passage-additional-mask-Boar.png",
        mask_b_name        = "Boar Mask",
        mask_s             = "Passage-additional-mask-Serow-icon-Morybel-0146.png",
        mask_s_real        = "Passage-additional-mask-Serow.png",
        mask_s_name        = "Serow Mask",
        mask_r		       = "Passage-additional-mask-Racoon-Morybel-0146.png",
        mask_r_real        = "Passage-additional-mask-Racoon.png",
        mask_r_side		   = "Passage-Guide-Raccoon-Mask-side.png",
        mask_r_name        = "Raccoon Mask",
        mask_m			   = "Passage-additional-mask-Monkey-Morybel-0146.png",
        mask_m_real        = "Passage-additional-mask-Monkey.png",
        mask_m_name        = "Monkey Mask",
        prop_h             = "Passage-Hacky-Sack-prop-icon-Morybel-0146.png",
        prop_h_real        = "Passage-Hacky-Sack-prop.png",
        prop_h_held		   = "Passage-Playing-With-Hacky-Sack-Prop.png",
        prop_h_back		   = "Passage-Hacky-Sack-prop-on-your-back.png",
        prop_h_name        = "Footbag",
        necklace_u_real    = "Passage-Seasonal-pendant.png",
        sh_icon            = "SOPassage-seasonal-heart-icon-Morybel-0146.png",
        sc_icon            = "SOPassage-seasonal-candle-icon-Morybel-0146.png",
    },
    moments = {
        name               = "Season of Moments",
        guide_name         = "Moments Guide",
        -- Setting guide_link means that this exists as a non-redirect spirit page
        guide_link         = "Moments Guide",
        short_name         = "Moments",
        icon               = "Season-of-Moments-icon.png",
        sort               = 18,
        hairpiece_u        = "Moments-Guide-Ultimate-Hair-accessory-icon-Credit-Morybel.png",
        hairpiece_u_real   = "Moments-Guide-Ultimate-Hair-accessory.png",        
        prop               = "Moments-Guide-Prop-Camera-icon-Credit-Morybel.png",
        prop_real          = "Moments-Guide-Prop-Camera.png",
        prop_name          = "Camera",
		prop_u             = "Moments-Guide-Prop-Ultimate-Camera-icon-Credit-Morybel.png",
		prop_u_real        = "Moments-Guide-Prop-Ultimate-Camera.png",
		prop_u_name        = "Moments Ultimate Camera",
		facepiece_u		   = "Moments-Guide-Head-accessory-icon-Credit-Morybel.png",
		facepiece_u_real   = "Moments-Guide-Head-accessory.png",
        necklace_u_real    = "Moments-Guide-Pendant.png",
        sh_icon            = "SOMoments-seasonal-heart-icon-Credit-Morybel.png",
        sc_icon            = "SOMoments-seasonal-candle-icon-Credit-Morybel.png",
    },
	revival = {
		name               = "Season of Revival",
		guide_name         = "Hopeful Steward",
		-- Setting guide_link means that this exists as a non-redirect spirit page
		guide_link         = "Hopeful Steward Ultimate Guide",
		alt_name           = { "Revival Ultimate Guide" },
		short_name         = "Revival",
		icon               = "Season-of-Revival-icon.png",
		sort               = 19,
		hair               = "Revival-Hair-icon.png",
        hair_real          = "Revival-Hair.png",
		hair_u             = "Revival-Ultimate-Hair-icon.png",
		hair_u_real        = "Revival-Ultimate-Hair-front.png",
		hair_u_side        = "Revival-Ultimate-Hair-side.png",
		hair_u_back        = "Revival-Ultimate-Hair-back.png",		
		cape_u             = "Revival-Ultimate-Cape-icon.png",
		cape_u_real        = "Revival-Ultimate-Cape-back.png",
		cape_u_front       = "Revival-Ultimate-Cape-front.png",
		cape_u_interior    = "Revival-Ultimate-Cape-front-interior.png",
		cape_u_exterior    = "Revival-Ultimate-Cape-back-exterior.png",		
		necklace_u_real    = "Season-of-Revival-Pendant.png",
		sh_icon            = "Revival-seasonal-heart-icon.png",
		sc_icon            = "Revival-seasonal-candle-icon.png",
	},
	the_nine_colored_deer = {
		name               = "Season of the Nine-Colored Deer",
		guide_name         = "Spirit of Mural",
		-- Setting guide_link means that this exists as a non-redirect spirit page
		guide_link         = "Spirit of Mural Ultimate Guide",
		short_name         = "the Nine-Colored Deer",
		alt_name           = { "The Nine-Colored Deer Ultimate Guide", "The Nine-Colored Deer", "Nine-Colored Deer", "the Nine Colored Deer", "The Nine Colored Deer", "Nine Colored Deer" },
		icon               = "Season-of-The-Nine-Colored-Deer-icon.png",
		sort               = 20,
		hairpiece          = "Nine-Colored-Deer-Hair-Accessory-icon.png",
        hairpiece_real     = "Nine-Colored-Deer-Hair-Accessory.png",
        mask               = "Nine-Colored-Deer-Mask-icon.png",
        mask_real          = "Nine-Colored-Deer-Mask.png",
		hair_u             = "Nine-Colored-Deer-Ultimate-Hair-icon.png",
		hair_u_real        = "Nine-Colored-Deer-Ultimate-Hair-front.png",
		hair_u_side        = "Nine-Colored-Deer-Ultimate-Hair-side.png",
		hair_u_back        = "Nine-Colored-Deer-Ultimate-Hair-back.png",
		outfit_u           = "Nine-Colored-Deer-Ultimate-Outfit-icon.png",
        outfit_u_real      = "Nine-Colored-Deer-Ultimate-Outfit.png",
        outfit_u_back	   = "Nine-Colored-Deer-Ultimate-Outfit-Back.png",
		cape_u             = "Nine-Colored-Deer-Ultimate-Cape-icon.png",
		cape_u_real        = "Nine-Colored-Deer-Ultimate-Cape-back.png",
		cape_u_front       = "Nine-Colored-Deer-Ultimate-Cape-front.png",
		cape_u_interior    = "Nine-Colored-Deer-Ultimate-Cape-front-interior.png",
		cape_u_exterior    = "Nine-Colored-Deer-Ultimate-Cape-back-exterior.png",
		--[=[
		r for Radiance of the Nine-Colored Deer IAP Cape
		g for Gift of the Nine-Colored Deer IAP Mask/Horns
		]=]		
		cape_r             = "Radiance-of-the-Nine-Colored-Deer-icon.png",
		cape_r_real        = "Radiance-of-the-Nine-Colored-Deer-back.png",
		cape_r_front       = "Radiance-of-the-Nine-Colored-Deer-front.png",
		cape_r_interior    = "Radiance-of-the-Nine-Colored-Deer-front-interior.png",
		cape_r_exterior    = "Radiance-of-the-Nine-Colored-Deer-back-exterior.png",
		mask_g             = "Gift-of-the-Nine-Colored-Deer-Mask-icon.png",
		mask_g_real        = "Gift-of-the-Nine-Colored-Deer-Mask.png",
		headpiece_g        = "Gift-of-the-Nine-Colored-Deer-Facepiece-icon.png",
		headpiece_g_real   = "Gift-of-the-Nine-Colored-Deer-Facepiece.png",
		necklace_u_real    = "Season-of-The-Nine-Colored-Deer-Pendant.png",
		sh_icon            = "Nine-Colored-Deer-seasonal-heart-icon.png",
		sc_icon            = "Nine-Colored-Deer-seasonal-candle-icon.png",
	},
	nesting = {
		name               = "Season of Nesting",
		guide_name         = "Nesting Guide",
		-- Setting guide_link means that this exists as a non-redirect spirit page
		guide_link         = "Nesting Guide",
		alt_name           = { "Nesting Ultimate Guide" },
		short_name         = "Nesting",
		icon               = "Season-of-Nesting-icon.png",
		sort               = 21,
		outfit_u		   = "Nesting-Ultimate-Outfit-icon.png",  
		outfit_u_real      = "Nesting-Ultimate-Outfit-front.png",
		outfit_u_back	   = "Nesting-Ultimate-Outfit-back.png",
		prop_u             = "Nesting-Guide-Mannequin-Figurine-Prop-icon.png",
		prop_u_real        = "Nesting-Guide-Mannequin-Figurine-Prop.png",
        prop_u_back        = "Nesting-Guide-Mannequin-Figurine-Prop-on-back.png",
		prop_u_name        = "Mini Figurine",
		necklace_u_real    = "Season-of-Nesting-Pendant.png",
		sh_icon            = "Season-of-Nesting-Seasonal-Heart-icon.png",
		sc_icon            = "Season-of-Nesting-Seasonal-Candle-icon.png",
	},
	duets = {
		name               = "Season of Duets",
		guide_name         = "Duets Guide",
		-- Setting guide_link means that this exists as a non-redirect spirit page
		guide_link         = "Duets Guide",
		alt_name           = { "Duets Ultimate Guide" },
		short_name         = "Duets",
		inst_name		   = "Duets Grand Piano",
		icon               = "Season-of-Duets-icon.png",
		sort               = 22,
		cape_u             = "Duets-Ultimate-Cape-icon.png",
		cape_u_real        = "Duets-Ultimate-Cape-back.png",
		cape_u_front       = "Duets-Ultimate-Cape-front.png",
		cape_u_interior    = "Duets-Ultimate-Cape-front-interior.png",
		cape_u_exterior    = "Duets-Ultimate-Cape-back-exterior.png",
		prop_u             = "Duets-Ultimate-Poster-Prop-icon.png",
		prop_u_real        = "Duets-Ultimate-Poster-Prop.png",
		prop_u_back        = "Duets-Poster-Props-Backpack.png",
		prop_u_name        = "Duets Ultimate Poster",
		instrument_u       = "Duets-Ultimate-Grand-Piano-Prop-icon.png",
		instrument_u_real  = "Duets-Ultimate-Grand-Piano-Prop.png",
		instrument_u_back  = "Duets-Ultimate-Grand-Piano-Prop-on-back.png",
		necklace_u_real    = "Season-of-Duets-Pendant.png",
		emote              = "Duets-Guide-Action-icon.png",
		emote_name         = "Duet Bow Action",
		mask               = "Duets-Guide-Mask-icon.png",
		mask_real          = "Duets-Mask-front.png",
		mask_side          = "Duets-Mask-side.png",
		sh_icon            = "Season-of-Duets-Seasonal-Heart-icon.png",
		sc_icon            = "Season-of-Duets-Seasonal-Candle-icon.png",
	},
	moomin = {
		name               = "Season of Moomin",
		guide_name         = "The Moomin Storybook",
		-- Setting guide_link means that this exists as a non-redirect spirit page
		guide_link         = "The Moomin Storybook",
		alt_name           = { "The Moomin Storybook Ultimate Guide", "Moomin Ultimate Guide", "Moomin Storybook Ultimate Guide", "Moomin Guide" },
		short_name         = "Moomin",
		icon               = "Season-of-Moomin-icon.png",
		sort               = 23,
		necklace_u_real    = "Season-of-Moomin-Pendant.png",
		sh_icon            = "Season-of-Moomin-Seasonal-Heart-icon.png",
		sc_icon            = "Season-of-Moomin-Seasonal-Candle-icon.png",
		outfit_u		   = "Moomin-Ultimate-Outfit-icon.png",  
		outfit_u_real      = "Moomin-Ultimate-Outfit-front.png",
		outfit_u_back	   = "Moomin-Ultimate-Outfit-back.png",
		prop_u             = "Moomin-Ultimate-Umbrella-Prop-icon.png",
		prop_u_real        = "Moomin-Ultimate-Umbrella-Prop.png",
		prop_u_held        = "Moomin-Ultimate-Umbrella-Prop-held.png",
		prop_u_back        = "Moomin-Ultimate-Umbrella-Prop-on-back.png",
		prop_u_name        = "Moomin Ultimate Umbrella",
		prop_m             = "Moomin-Ultimate-Plush-Prop-icon.png",
		prop_m_real        = "Moomin-Ultimate-Plush-Prop.png",
		prop_m_back        = "Moomin-Ultimate-Plush-Prop-on-back.png",
		prop_m_held		   = "Moomin-Ultimate-Plush-Prop-held.png",
		prop_m_name        = "Moomin Ultimate Plush",
		emote              = "The-Moomin-Storybook-Emote-icon.png",
		emote_name         = "Read",
		--[=[
		i for invisible (IGC Outfit)
		p for painting (IGC Prop)
		]=]
		outfit_i		   = "Moomin-Invisible-Outfit-icon.png",  
		outfit_i_real      = "Moomin-Invisible-Outfit-front.png",
		outfit_i_back	   = "Moomin-Invisible-Outfit-back.png",	
		prop_p             = "Moomin-Family-Painting-Prop-icon.png",
		prop_p_real        = "Moomin-Family-Painting-Prop.png",
		prop_p_back        = "Duets-Poster-Props-Backpack.png",
		prop_p_name        = "Moomin Family Painting",	
		--[=[
		n for Ninny (IAP Cape)
		m for Moomintroll (Ears, Tail)
		h for Hattifattener (IAP Shoulder Buddy)
		s for Snufkin (IAP Outfit, Neck Accessory, Hat)
		]=]
		cape_n             = "Moominmammas-Masterpiece-icon.png",
		cape_n_real        = "Moominmammas-Masterpiece-back.png",
		cape_n_front       = "Moominmammas-Masterpiece-front.png",
        cape_n_interior    = "Moominmammas-Masterpiece-interior.png",
        cape_n_exterior    = "Moominmammas-Masterpiece-exterior.png",
		cape_n_name		   = "Moominmamma's Masterpiece",
		hairpiece_m        = "Moomintroll-Ears-Accessory-icon.png",
		hairpiece_m_real   = "Moomintroll-Ears-Accessory.png",
		hairpiece_m_name   = "Moomintroll Ears",
		--  // Unsure if tail will change its closet category
		neckpiece_m        = "Moomintroll-Tail-Accessory-icon.png",
		neckpiece_m_real   = "Moomintroll-Tail-Accessory.png",
		neckpiece_m_name   = "Moomintroll Tail",
		neckpiece_h        = "Hattifattener-Shoulder-Buddy-icon.png",
		neckpiece_h_real   = "Hattifattener-Shoulder-Buddy.png",
		neckpiece_h_name   = "Hattifattener Shoulder Buddy",
		outfit_s		   = "Roving-Snufkin-Robe-icon.png",  
		outfit_s_real      = "Roving-Snufkin-Robe-front.png",
		outfit_s_back	   = "Roving-Snufkin-Robe-back.png",
		outfit_s_name	   = "Roving Snufkin Robe",
		neckpiece_s		   = "Roving-Snufkin-Scarf-icon.png",
		neckpiece_s_real   = "Roving-Snufkin-Scarf.png",
		neckpiece_s_name   = "Roving Snufkin Scarf",
		hairpiece_s		   = "Pointed-Snufkin-Hat-icon.png",
		hairpiece_s_real   = "Pointed-Snufkin-Hat.png",
		hairpiece_s_name   = "Pointed Snufkin Hat",
	},
	radiance = {
		name               = "Season of Radiance",
		guide_name         = "Radiance Guide",
		-- Setting guide_link means that this exists as a non-redirect spirit page
		guide_link         = "Radiance Guide",
		short_name         = "Radiance",
		icon               = "Season-of-Radiance-icon.png",
		sort               = 24,
		cape_u             = "Radiance-Ultimate-Cape-icon.png",
		cape_u_real        = "Radiance-Ultimate-Cape-back.png",
		cape_u_front       = "Radiance-Ultimate-Cape-front.png",
		cape_u_interior    = "Radiance-Ultimate-Cape-front-interior.png",
		cape_u_exterior    = "Radiance-Ultimate-Cape-back-exterior.png",
		mask_u			   = "Radiance-Ultimate-Mask-icon.png",
		mask_u_real		   = "Radiance-Ultimate-Mask-front.png",
		mask_u_side		   = "Radiance-Ultimate-Mask-side.png",
		necklace_u_real    = "Season-of-Radiance-Pendant.png",
		cape_a             = "Season-of-Radiance-additional-Cape-icon.png",
		cape_a_real        = "Season-of-Radiance-additional-Cape-back.png",
		cape_a_front       = "Season-of-Radiance-additional-Cape-front.png",
		cape_a_interior    = "Season-of-Radiance-additional-Cape-front-interior.png",
		cape_a_exterior    = "Season-of-Radiance-additional-Cape-back-exterior.png",
		sh_icon            = "Season-of-Radiance-Seasonal-Heart-icon.png",
		sc_icon            = "Season-of-Radiance-Seasonal-Candle-icon.png",
	},
    the_blue_bird = {
		name               = "Season of the Blue Bird",
		guide_name         = "Blue Bird Guide",
		-- Setting guide_link means that this exists as a non-redirect spirit page
		guide_link         = "Blue Bird Guide",
		short_name         = "Blue Bird",
		alt_name           = { "The Blue Bird Ultimate Guide", "The Blue Bird", "Blue Bird", "the Blue Bird"},
		icon               = "Season-of-Blue-Bird-icon.png",
		sort               = 25,
		emote              = "Blue-Bird-Guide-ultimate-expression.png",
		emote_name         = "Cough",
		-- s for stance
		-- c for call
		emote_s            = "Blue-Bird-Sad-Stance-icon.png",
		emote_s_name       = "Despondent Stance",
		emote_c            = "Blue-Bird-Call.png",
		emote_c_name       = "Blue Bird Call",
		cape_u             = "Blue-Bird-Guide-Ultimate-Cape-icon.png",
		cape_u_real        = "Blue-Bird-Guide-Ultimate-Cape-back.png",
		cape_u_front       = "Blue-Bird-Guide-Ultimate-Cape-front.png",
		cape_u_interior    = "Blue-Bird-Guide-Ultimate-Cape-interior.png",
		cape_u_exterior    = "Blue-Bird-Guide-Ultimate-Cape-exterior.png",
		facepiece_u        = "Blue-Bird-Guide-Ultimate-Facepiece-icon.png",    
		facepiece_u_real   = "Blue-Bird-Guide-Ultimate-Facepiece.png", 
		prop_a             = "Blue-Bird-Guide-Additional-Prop-icon.png",
		prop_a_name        = "Tree Perch",
		prop_a_real        = "Blue-Bird-Guide-Prop.png",		
		prop_a_using	   = "Blue-Bird-Guide-Prop-Using.png",
		prop_a_back		   = "Blue-Bird-Guide-Prop-back.png",
		necklace_u_real    = "Season-of-the-Blue-Bird-Pendant.png",
		sh_icon            = "Blue-Bird-seasonal-heart-icon.png",
		sc_icon            = "Blue-Bird-seasonal-candle-icon.png",
	},
	the_two_embers_part_1 = {
	 	name               = "Season of The Two Embers - Part 1",
	 	guide_name         = "Vault Elder's Lantern",
		-- Setting guide_link means that this exists as a non-redirect spirit page
		guide_link         = "Vault Elder's Lantern",
		alt_name           = { "Two Embers Guide", "Elder's Lantern", "Two Embers Part 1 Guide" },
	 	short_name         = "Two Embers Part 1",
		--	inst_name          = "",
	 	icon               = "Season-of-the-Two-Embers-icon.png",
		sort               = 26,
		hairpiece_u        = "Vault-Elder-Lantern-Ultimate-Constellation-Hairpiece-icon.png",
		hairpiece_u_real   = "Vault-Elder-Lantern-Ultimate-Constellation-Hairpiece.png",
		hairpiece_u_back   = "Vault-Elder-Lantern-Ultimate-Constellation-Hairpiece-back.png",
		cape_u             = "Vault-Elder-Lantern-Ultimate-Cape-icon.png",
		cape_u_real        = "Vault-Elder-Lantern-Ultimate-Cape-back.png",
		cape_u_front       = "Vault-Elder-Lantern-Ultimate-Cape-front.png",
    	cape_u_interior    = "Vault-Elder-Lantern-Ultimate-Cape-interior.png",
    	cape_u_exterior    = "Vault-Elder-Lantern-Ultimate-Cape-exterior.png",
		prop_a             = "Season-of-Ember-P1-movie-poster-icon.png",
		prop_a_real        = "Season-of-Ember-P1-movie-poster.png",
		prop_a_back        = "Season-of-Ember-P1-movie-poster-wearing.png",
		prop_a_name        = "Two Embers Poster",
		necklace_u		   = "Season-of-the-Two-Embers-icon.png",
		necklace_u_real    = "Season-of-Ember-P1-Pendant.png",
		sh_icon            = "Season-of-Two-Embers-P1-Seasonal-Heart-icon.png",
		sc_icon            = "Season-of-Two-Embers-P1-Seasonal-Candle-icon.png",
		--[=[
		d for Darkness (IAP Cape)
		b for Blossom (IAP hairpiece)
		m for Mini Manatee (IAP hairpiece)
		p for (Manatee) Plush (IAP prop)
		s for Spirited (IAP necklace and headpiece)
		v for Vestige (IAP necklace and headpiece)
		]=]
		cape_d             = "Cloak-of-Darkness-Cape-icon.png",
		cape_d_real        = "Cloak-of-Darkness-Cape-back.png",
		cape_d_front       = "Cloak-of-Darkness-Cape-front.png",
    	cape_d_interior    = "Cloak-of-Darkness-Cape-interior.png",
    	cape_d_exterior    = "Cloak-of-Darkness-Cape-exterior.png",
    	cape_d_name		   = "Cloak of Darkness",
    	hairpiece_b        = "Butterfly-Blossom-Memento-Hairpiece-icon.png",
		hairpiece_b_real   = "Butterfly-Blossom-Memento-Hairpiece.png",
		hairpiece_b_side   = "Butterfly-Blossom-Memento-Hairpiece-side.png",
		hairpiece_b_name   = "Butterfly Blossom Memento",
		hairpiece_m        = "Mini-Manatee-Hairpiece-icon.png",
		hairpiece_m_real   = "Mini-Manatee-Hairpiece.png",
		hairpiece_m_name   = "Mini Manatee Accessory",
		prop_p             = "Manatee-Plush-Prop-icon.png",
		prop_p_real        = "Manatee-Plush-Prop.png",
		prop_p_back        = "Manatee-Plush-Prop-back.png",
		prop_p_held		   = "Manatee-Plush-Prop-using.png",
		prop_p_name        = "Manatee Plush",
		headpiece_s        = "Spirited-Manatee-Head-accessory-icon.png",
		headpiece_s_real   = "Spirited-Manatee-Headpiece.png",
		headpiece_s_name   = "Spirited Manatee Ears",
		--  // Unsure if tail will change its closet category
		neckpiece_s        = "Spirited-Manatee-Tail-icon.png",
		neckpiece_s_real   = "Spirited-Manatee-Tail.png",
		neckpiece_s_name   = "Spirited Manatee Tail",
		headpiece_v_iap    = "Vestige-of-Dark-Dragon-headpiece-IAP.png",
		headpiece_v		   = "Vestige-of-Dark-Dragon-headpiece-icon.png",
		headpiece_v_real   = "Vestige-of-Dark-Dragon-headpiece.png",
		headpiece_v_side   = "Vestige-of-Dark-Dragon-headpiece-side.png",
		headpiece_v_spell  = "Vestige-of-Dark-Dragon-headpiece-spell.png",	
		headpiece_v_name   = "Vestige of Dark Dragon Horns",
		--  // Unsure if tail will change its closet category
		neckpiece_v     	= "Vestige-of-Dark-Dragon-Tail-icon.png",
		neckpiece_v_real	= "Vestige-of-Dark-Dragon-Tail.png",
		neckpiece_v_spell	= "Vestige-of-Dark-Dragon-Tail-spell.png",	
		neckpiece_v_name	= "Vestige of Dark Dragon Tail",
		--  // M for memories since prop_p is already in use
		prop_m				= "Projector-of-Memories-Icon.png";
		prop_m_name			= "Projector of Memories";
		prop_m_real			= "Projector-of-Memories-prop.png";
		prop_m_back			= "Projector-of-Memories-back.png";
		prop_m_using		= "Projector-of-Memories-using.png";
		prop_m_spell		= "Projector-of-Memories-Spell.png";
		prop_m_iap			= "Projector-of-Memories-IAP.png";
	 },
	 
	 migration = {
        name                = "Season of Migration",
        short_name			= "Migration",
		guide_name          = "Migration Guide",
		-- Setting guide_link means that this exists as a non-redirect spirit page
		guide_link          = "Migration Guide",        
        icon				= "Season-of-Migration-icon.png",
		necklace_u_real		= "Migrating-Guide-Ultimate-Necklace.png",
		facepiece_u			= "Migrating-Guide-Ultimate-Face-Accessory-icon.png",		
		facepiece_u_real	= "Migrating-Guide-Ultimate-Face-Accessory.png",
		facepiece_u_front	= "Migrating-Guide-Ultimate-Face-Accessory-with-light-on.png",
		outfit_u			= "Migrating-Guide-Ultimate-Outfit-icon.png",
		outfit_u_real		= "Migrating-Guide-Ultimate-Outfit-front.png",		
		outfit_u_back		= "Migrating-Guide-Ultimate-Outfit-back.png",
		shoes_u				= "Migrating-Guide-Ultimate-Shoes-icon.png",		
		shoes_u_real		= "Migrating-Guide-Ultimate-Shoes.png",
		sh_icon             = "Season-of-Migration-Heart.png",
		sc_icon             = "Season-of-Migration-Candle.png",		
        sort				=  27,
    },
	 
    -- Format, use Ctrl+/ to toggle the comment
	-- the_season_name!change_this = {
	-- 	name               = "Season of ",
	-- 	guide_name         = " Guide",
	-- 	-- Setting guide_link means that this exists as a non-redirect spirit page
	-- 	guide_link         = " Guide",
	--	alt_name           = { "" },
	-- 	short_name         = "",
	--	inst_name          = "",
	-- 	icon               = ".png",
	-- 	sort               = ,
	--	hair_u             = "",
	--  hair_u_real        = "",
	--	headpiece_u        = "",
	--	headpiece_u_real   = "",
	--	cape_u             = "",
	--	cape_u_real        = "",
	--  cape_u_front       = "",
    --  cape_u_interior    = "",
    --  cape_u_exterior    = "",
	--	mask_u             = "",
	--	mask_u_real        = "",
	--	outfit_u		   = "",  
	--	outfit_u_real      = "",
	--  outfit_u_back	   = "",
	--	neckpiece_u        = "",
	--	neckpiece_u_real   = "",
	--	prop_u             = "",
	--	prop_u_real        = "",
	--  prop_u_name        = "",
	--	intrument_u        = "",
	--	intrument_u_real   = "",
	--  necklace_u_real    = "",
	-- 	sh_icon            = "-seasonal-heart-icon-Morybel-0146.png",
	-- 	sc_icon            = "-seasonal-candle-icon-Morybel-0146.png",
	-- },
}

local stdData = require('Module:stdData')
-- Process data, including merging in language-specific overrides
return stdData.processData(data, 'Seasons')